export const mockCredits = {
    "id": 337404,
    "cast": [
        {
            "adult": false,
            "gender": 1,
            "id": 54693,
            "known_for_department": "Acting",
            "name": "Emma Stone",
            "original_name": "Emma Stone",
            "popularity": 41.083,
            "profile_path": "/2hwXbPW2ffnXUe1Um0WXHG0cTwb.jpg",
            "cast_id": 0,
            "character": "Estella / Cruella",
            "credit_id": "59a50d419251412f02004a64",
            "order": 0
        },
        {
            "adult": false,
            "gender": 1,
            "id": 7056,
            "known_for_department": "Acting",
            "name": "Emma Thompson",
            "original_name": "Emma Thompson",
            "popularity": 7.764,
            "profile_path": "/xr8Ki3CIqweWWqS5q0kUYdiK6oQ.jpg",
            "cast_id": 11,
            "character": "The Baroness",
            "credit_id": "5d3f84f060b58d00106bb4b0",
            "order": 1
        },
        {
            "adult": false,
            "gender": 2,
            "id": 54811,
            "known_for_department": "Acting",
            "name": "Joel Fry",
            "original_name": "Joel Fry",
            "popularity": 7.734,
            "profile_path": "/4nEKEWJpaTHncCTv6zeP98V0qGI.jpg",
            "cast_id": 13,
            "character": "Jasper",
            "credit_id": "5d4b212953f83314d5d339b2",
            "order": 2
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1294982,
            "known_for_department": "Acting",
            "name": "Paul Walter Hauser",
            "original_name": "Paul Walter Hauser",
            "popularity": 4.659,
            "profile_path": "/hV2oiKF2xlDMXtuq3Si1TA4b6DA.jpg",
            "cast_id": 12,
            "character": "Horace",
            "credit_id": "5d3f8503b87aec037938ec3d",
            "order": 3
        },
        {
            "adult": false,
            "gender": 2,
            "id": 2983,
            "known_for_department": "Acting",
            "name": "Mark Strong",
            "original_name": "Mark Strong",
            "popularity": 14.312,
            "profile_path": "/pw6AvwaBbr44Nje9JQMBBwhchiu.jpg",
            "cast_id": 30,
            "character": "John the Valet",
            "credit_id": "602d2f3b44ea54003fd4a042",
            "order": 4
        },
        {
            "adult": false,
            "gender": 1,
            "id": 2163852,
            "known_for_department": "Acting",
            "name": "Tipper Seifert-Cleveland",
            "original_name": "Tipper Seifert-Cleveland",
            "popularity": 2.425,
            "profile_path": "/yJTIExQYXMeNdY6s9ZZ9VUkQxQS.jpg",
            "cast_id": 36,
            "character": "Estella (12 yrs)",
            "credit_id": "60ae527705b54900290d8a48",
            "order": 5
        },
        {
            "adult": false,
            "gender": 1,
            "id": 1532312,
            "known_for_department": "Acting",
            "name": "Kirby Howell-Baptiste",
            "original_name": "Kirby Howell-Baptiste",
            "popularity": 3.669,
            "profile_path": "/neWSyBmw5q2JJiOAXWk4lvWJGlY.jpg",
            "cast_id": 15,
            "character": "Anita Darling",
            "credit_id": "5d8aa756abf8e2000f77166e",
            "order": 6
        },
        {
            "adult": false,
            "gender": 1,
            "id": 130414,
            "known_for_department": "Acting",
            "name": "Emily Beecham",
            "original_name": "Emily Beecham",
            "popularity": 4.67,
            "profile_path": "/knR5avTlO4Xnxw7Nc3xxUj3rtjh.jpg",
            "cast_id": 14,
            "character": "Catherine",
            "credit_id": "5d84e760109dec0252cc3ef9",
            "order": 7
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1819918,
            "known_for_department": "Acting",
            "name": "John McCrea",
            "original_name": "John McCrea",
            "popularity": 3.365,
            "profile_path": "/lj2qUd1TxeCY0G76QZF4dRKdHZ1.jpg",
            "cast_id": 33,
            "character": "Artie",
            "credit_id": "606dffa9e1ad790040b0759d",
            "order": 8
        },
        {
            "adult": false,
            "gender": 2,
            "id": 2959,
            "known_for_department": "Acting",
            "name": "Kayvan Novak",
            "original_name": "Kayvan Novak",
            "popularity": 4.222,
            "profile_path": "/bjOKpuBWgLdF8WV1M8SE7C7xNea.jpg",
            "cast_id": 35,
            "character": "Roger",
            "credit_id": "60ae525d0f2ae1003f4f5431",
            "order": 9
        },
        {
            "adult": false,
            "gender": 0,
            "id": 1470911,
            "known_for_department": "Acting",
            "name": "Jamie Demetriou",
            "original_name": "Jamie Demetriou",
            "popularity": 3.43,
            "profile_path": "/owXXYV1MNijRAVJV2Q47WEWT9Wv.jpg",
            "cast_id": 32,
            "character": "Gerald",
            "credit_id": "6041baba5690b5005a064f0d",
            "order": 10
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1432064,
            "known_for_department": "Directing",
            "name": "Abraham Popoola",
            "original_name": "Abraham Popoola",
            "popularity": 0.98,
            "profile_path": "/qOTrfglDJaGLW3EipLL6k65Jpns.jpg",
            "cast_id": 34,
            "character": "George",
            "credit_id": "606dffc109c24c0058439473",
            "order": 11
        },
        {
            "adult": false,
            "gender": 2,
            "id": 29237,
            "known_for_department": "Acting",
            "name": "Leo Bill",
            "original_name": "Leo Bill",
            "popularity": 0.933,
            "profile_path": "/lyXVnrvrbtAr5pPKaqGHQfe1a7W.jpg",
            "cast_id": 39,
            "character": "Headmaster",
            "credit_id": "60b161605b07140040b62565",
            "order": 12
        },
        {
            "adult": false,
            "gender": 0,
            "id": 1333631,
            "known_for_department": "Acting",
            "name": "Javone Prince",
            "original_name": "Javone Prince",
            "popularity": 0.98,
            "profile_path": null,
            "cast_id": 40,
            "character": "Ipswich Manor Security Guard",
            "credit_id": "60b1619c72d855004072b39b",
            "order": 13
        },
        {
            "adult": false,
            "gender": 0,
            "id": 62973,
            "known_for_department": "Acting",
            "name": "Steve Edge",
            "original_name": "Steve Edge",
            "popularity": 0.6,
            "profile_path": null,
            "cast_id": 41,
            "character": "Steven the Jewellery Shop Assistant",
            "credit_id": "60b161c2957e6d002a2b4d8d",
            "order": 14
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1123187,
            "known_for_department": "Acting",
            "name": "Paul Chowdhry",
            "original_name": "Paul Chowdhry",
            "popularity": 1.38,
            "profile_path": "/qgxjP7pS8MtUwfHEvstInC4Jxcr.jpg",
            "cast_id": 42,
            "character": "Restaurant Owner",
            "credit_id": "60b162019dee580057addb4c",
            "order": 15
        },
        {
            "adult": false,
            "gender": 0,
            "id": 3106896,
            "known_for_department": "Acting",
            "name": "Ziggy Gardner",
            "original_name": "Ziggy Gardner",
            "popularity": 0.6,
            "profile_path": null,
            "cast_id": 43,
            "character": "Jasper (12 yrs)",
            "credit_id": "60b162a572d855002ad10f65",
            "order": 16
        },
        {
            "adult": false,
            "gender": 0,
            "id": 3106897,
            "known_for_department": "Acting",
            "name": "Joseph MacDonald",
            "original_name": "Joseph MacDonald",
            "popularity": 0.6,
            "profile_path": null,
            "cast_id": 44,
            "character": "Horace (12 yrs)",
            "credit_id": "60b1633a945c20005810cb80",
            "order": 17
        },
        {
            "adult": false,
            "gender": 1,
            "id": 2451439,
            "known_for_department": "Acting",
            "name": "Niamh Lynch",
            "original_name": "Niamh Lynch",
            "popularity": 0.6,
            "profile_path": "/aiLxUTc8EE2MG49oMN39y1HgkUD.jpg",
            "cast_id": 45,
            "character": "Liberty Shop Girl",
            "credit_id": "60b25fc4c09e99004027be68",
            "order": 18
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1312526,
            "known_for_department": "Acting",
            "name": "Andrew Leung",
            "original_name": "Andrew Leung",
            "popularity": 5.866,
            "profile_path": "/hXK4gUIooj3SpQ2qwEN9JLV0B7d.jpg",
            "cast_id": 46,
            "character": "Jeffrey",
            "credit_id": "60b25fe1a06645002a512746",
            "order": 19
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1349801,
            "known_for_department": "Acting",
            "name": "Ed Birch",
            "original_name": "Ed Birch",
            "popularity": 0.612,
            "profile_path": "/k3CBVC3PVrcih7Q9xlySlqE8pMh.jpg",
            "cast_id": 47,
            "character": "Baroness Head of Security",
            "credit_id": "60b260873520e800405fe471",
            "order": 20
        },
        {
            "adult": false,
            "gender": 0,
            "id": 1503746,
            "known_for_department": "Acting",
            "name": "Dylan Lowe",
            "original_name": "Dylan Lowe",
            "popularity": 0.6,
            "profile_path": null,
            "cast_id": 48,
            "character": "Mean Ginger",
            "credit_id": "60b260ae477215002a83fe13",
            "order": 21
        },
        {
            "adult": false,
            "gender": 2,
            "id": 110075,
            "known_for_department": "Acting",
            "name": "Paul Bazely",
            "original_name": "Paul Bazely",
            "popularity": 1.22,
            "profile_path": "/t0zvUJWzMCOqpDfQRKbeTTkhqt3.jpg",
            "cast_id": 49,
            "character": "Police Commissioner",
            "credit_id": "60b260c9477215005802ec46",
            "order": 22
        },
        {
            "adult": false,
            "gender": 1,
            "id": 2160734,
            "known_for_department": "Acting",
            "name": "Ninette Finch",
            "original_name": "Ninette Finch",
            "popularity": 0.6,
            "profile_path": "/d1m2HVDDOfVtfUDQGbAS3qZPnrl.jpg",
            "cast_id": 50,
            "character": "Lady",
            "credit_id": "60b260e9b7b69d0057c35e78",
            "order": 23
        },
        {
            "adult": false,
            "gender": 1,
            "id": 1356007,
            "known_for_department": "Acting",
            "name": "Sarah Crowden",
            "original_name": "Sarah Crowden",
            "popularity": 2.11,
            "profile_path": "/3mc7xMh0hGsHPuxCKjJtHQ7viYH.jpg",
            "cast_id": 51,
            "character": "Beehive Lady",
            "credit_id": "60b260fac490480040f9d7bb",
            "order": 24
        },
        {
            "adult": false,
            "gender": 0,
            "id": 3107557,
            "known_for_department": "Acting",
            "name": "Harrison Willmott",
            "original_name": "Harrison Willmott",
            "popularity": 0.6,
            "profile_path": null,
            "cast_id": 52,
            "character": "Mean Kid",
            "credit_id": "60b2612a477215002a83fec1",
            "order": 25
        },
        {
            "adult": false,
            "gender": 2,
            "id": 2426997,
            "known_for_department": "Acting",
            "name": "Jack Barry",
            "original_name": "Jack Barry",
            "popularity": 0.6,
            "profile_path": "/A1YjxMNVt3LWcIRrAb3RW2WEc2q.jpg",
            "cast_id": 53,
            "character": "Restaurant Valet",
            "credit_id": "60b261b8c49048002a0f3c2a",
            "order": 26
        },
        {
            "adult": false,
            "gender": 1,
            "id": 2486152,
            "known_for_department": "Acting",
            "name": "Asmara Gabrielle",
            "original_name": "Asmara Gabrielle",
            "popularity": 0.6,
            "profile_path": null,
            "cast_id": 54,
            "character": "Teacher",
            "credit_id": "60b261c6bf31f2007a3b8cfe",
            "order": 27
        },
        {
            "adult": false,
            "gender": 0,
            "id": 1593293,
            "known_for_department": "Acting",
            "name": "Tom Turner",
            "original_name": "Tom Turner",
            "popularity": 0.6,
            "profile_path": "/wtL9eRpelekpa3Fbmql297BcpGJ.jpg",
            "cast_id": 55,
            "character": "The Baron",
            "credit_id": "60b261e262e86f002b3b460b",
            "order": 28
        }
    ],
    "crew": [
        {
            "adult": false,
            "gender": 1,
            "id": 515,
            "known_for_department": "Acting",
            "name": "Glenn Close",
            "original_name": "Genn Closle",
            "popularity": 3.727,
            "profile_path": "/bjb2dExzz0EWK4fnhfb7zs2CoEZ.jpg",
            "credit_id": "602d2d7cd4b9d90041d22497",
            "department": "Production",
            "job": "Executive Producer"
        },
        {
            "adult": false,
            "gender": 1,
            "id": 33685,
            "known_for_department": "Editing",
            "name": "Tatiana S. Riegel",
            "original_name": "Tatiana S. Riegel",
            "popularity": 1.4,
            "profile_path": "/mms5qpMvookGWLw2UZ54QqO9hES.jpg",
            "credit_id": "60aeaa775684630029427b4a",
            "department": "Editing",
            "job": "Editor"
        },
        {
            "adult": false,
            "gender": 1,
            "id": 10567,
            "known_for_department": "Writing",
            "name": "Aline Brosh McKenna",
            "original_name": "Aline Brosh McKenna",
            "popularity": 0.6,
            "profile_path": null,
            "credit_id": "602d2eeca6ddcb004059406a",
            "department": "Writing",
            "job": "Story"
        },
        {
            "adult": false,
            "gender": 1,
            "id": 17166,
            "known_for_department": "Costume & Make-Up",
            "name": "Jenny Beavan",
            "original_name": "Jenny Beavan",
            "popularity": 1.087,
            "profile_path": null,
            "credit_id": "602d2df7223e20003e968eee",
            "department": "Costume & Make-Up",
            "job": "Costume Design"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 23485,
            "known_for_department": "Production",
            "name": "Marc Platt",
            "original_name": "Marc Platt",
            "popularity": 1.4,
            "profile_path": "/1V51JQqDdoXnC4LElFfSPSjYGfY.jpg",
            "credit_id": "602d2dce8e2ba6004014604d",
            "department": "Production",
            "job": "Producer"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 45398,
            "known_for_department": "Acting",
            "name": "Steve Zissis",
            "original_name": "Steve Zissis",
            "popularity": 1.002,
            "profile_path": "/hiaDKTWD9dziiMjSDbCDh7bltDU.jpg",
            "credit_id": "602d2f07db4ed600416c2eae",
            "department": "Writing",
            "job": "Story"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 50767,
            "known_for_department": "Directing",
            "name": "Craig Gillespie",
            "original_name": "Craig Gillespie",
            "popularity": 1.24,
            "profile_path": "/pVHspL9QWsXCm3t3VXEaCJ9y8Zz.jpg",
            "credit_id": "5c072e3492514111160d7f8a",
            "department": "Directing",
            "job": "Director"
        },
        {
            "adult": false,
            "gender": 1,
            "id": 54693,
            "known_for_department": "Acting",
            "name": "Emma Stone",
            "original_name": "Emma Stone",
            "popularity": 41.083,
            "profile_path": "/2hwXbPW2ffnXUe1Um0WXHG0cTwb.jpg",
            "credit_id": "602d2d726743fa003fe3e46d",
            "department": "Production",
            "job": "Executive Producer"
        },
        {
            "adult": false,
            "gender": 1,
            "id": 56718,
            "known_for_department": "Writing",
            "name": "Dana Fox",
            "original_name": "Dana Fox",
            "popularity": 3.314,
            "profile_path": null,
            "credit_id": "602d2eaf6743fa003de429c4",
            "department": "Writing",
            "job": "Screenplay"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 64830,
            "known_for_department": "Production",
            "name": "Andrew Gunn",
            "original_name": "Andrew Gunn",
            "popularity": 0.6,
            "profile_path": null,
            "credit_id": "5bb300c99251411ca3004b59",
            "department": "Production",
            "job": "Producer"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 77723,
            "known_for_department": "Writing",
            "name": "Tony McNamara",
            "original_name": "Tony McNamara",
            "popularity": 1.017,
            "profile_path": "/xqvrpLtpYCOMbMkySCjcsavYGur.jpg",
            "credit_id": "602d2edf223e200040978d68",
            "department": "Writing",
            "job": "Screenplay"
        },
        {
            "adult": false,
            "gender": 0,
            "id": 236909,
            "known_for_department": "Camera",
            "name": "Nicolas Karakatsanis",
            "original_name": "Nicolas Karakatsanis",
            "popularity": 0.98,
            "profile_path": null,
            "credit_id": "602d325da6ddcb003e58e056",
            "department": "Camera",
            "job": "Director of Photography"
        },
        {
            "adult": false,
            "gender": 1,
            "id": 940376,
            "known_for_department": "Writing",
            "name": "Kelly Marcel",
            "original_name": "Kelly Marcel",
            "popularity": 0.6,
            "profile_path": "/thpdVW7O1975GcA3eNs1H8UIlmd.jpg",
            "credit_id": "602d2ef9e86017003dff4016",
            "department": "Writing",
            "job": "Story"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 1533516,
            "known_for_department": "Sound",
            "name": "Nicholas Britell",
            "original_name": "Nicholas Britell",
            "popularity": 0.6,
            "profile_path": "/6xbBWMcup9MQlkdNvbsA4bhzYVp.jpg",
            "credit_id": "60aeaa51fcf9070040c6afb4",
            "department": "Sound",
            "job": "Music"
        },
        {
            "adult": false,
            "gender": 1,
            "id": 1564277,
            "known_for_department": "Production",
            "name": "Michelle Wright",
            "original_name": "Michelle Wright",
            "popularity": 0.6,
            "profile_path": null,
            "credit_id": "602d2da5223e20003f96e010",
            "department": "Production",
            "job": "Executive Producer"
        },
        {
            "adult": false,
            "gender": 0,
            "id": 1974502,
            "known_for_department": "Production",
            "name": "Jared LeBoff",
            "original_name": "Jared LeBoff",
            "popularity": 0.6,
            "profile_path": null,
            "credit_id": "602d2d91cedac400405104a9",
            "department": "Production",
            "job": "Executive Producer"
        },
        {
            "adult": false,
            "gender": 0,
            "id": 2109201,
            "known_for_department": "Production",
            "name": "Kristin Burr",
            "original_name": "Kristin Burr",
            "popularity": 0.6,
            "profile_path": null,
            "credit_id": "602d2ddd223e20003d970777",
            "department": "Production",
            "job": "Producer"
        }
    ]
}

export const mockMovie =
{
    "adult": false,
    "backdrop_path": "/8ChCpCYxh9YXusmHwcE9YzP0TSG.jpg",
    "belongs_to_collection": {
        "id": 837007,
        "name": "Cruella Collection",
        "poster_path": null,
        "backdrop_path": null
    },
    "budget": 200000000,
    "genres": [
        {
            "id": 35,
            "name": "Comedy"
        },
        {
            "id": 80,
            "name": "Crime"
        }
    ],
    "homepage": "https://movies.disney.com/cruella",
    "id": 337404,
    "imdb_id": "tt3228774",
    "original_language": "en",
    "original_title": "Cruella",
    "overview": "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
    "popularity": 4774.831,
    "poster_path": "/rTh4K5uw9HypmpGslcKd4QfHl93.jpg",
    "production_companies": [
        {
            "id": 2,
            "logo_path": "/wdrCwmRnLFJhEoH8GSfymY85KHT.png",
            "name": "Walt Disney Pictures",
            "origin_country": "US"
        }
    ],
    "production_countries": [
        {
            "iso_3166_1": "US",
            "name": "United States of America"
        }
    ],
    "release_date": "2021-05-26",
    "revenue": 129300000,
    "runtime": 134,
    "spoken_languages": [
        {
            "english_name": "English",
            "iso_639_1": "en",
            "name": "English"
        }
    ],
    "status": "Released",
    "tagline": "Hello Cruel World",
    "title": "Cruella",
    "video": false,
    "vote_average": 8.6,
    "vote_count": 2689
};
export const data = {
    "page": 1,
    "results": [
        {
            "original_title": "Wonder Woman 1984",
            "id": 464052,
            "video": false,
            "title": "Wonder Woman 1984",
            "overview": "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
            "release_date": "2020-12-16",
            "vote_count": 1879,
            "adult": false,
            "backdrop_path": "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
            "vote_average": 7.3,
            "genre_ids": [
                14,
                28,
                12
            ],
            "poster_path": "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
            "original_language": "en",
            "popularity": 7842.973,
            "media_type": "movie"
        },
        {
            "vote_average": 8.5,
            "title": "Soul",
            "overview": "Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.",
            "release_date": "2020-12-25",
            "adult": false,
            "backdrop_path": "/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg",
            "genre_ids": [
                16,
                35,
                18,
                10402,
                14
            ],
            "vote_count": 2299,
            "original_language": "en",
            "original_title": "Soul",
            "poster_path": "/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
            "id": 508442,
            "video": false,
            "popularity": 5329.953,
            "media_type": "movie"
        },
        {
            "genre_ids": [
                28,
                53,
                878
            ],
            "original_language": "en",
            "original_title": "Tenet",
            "poster_path": "/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
            "video": false,
            "title": "Tenet",
            "vote_count": 3532,
            "overview": "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
            "release_date": "2020-08-22",
            "id": 577922,
            "vote_average": 7.4,
            "adult": false,
            "backdrop_path": "/wzJRB4MKi3yK138bJyuL9nx47y6.jpg",
            "popularity": 1813.149,
            "media_type": "movie"
        },
        {
            "original_language": "en",
            "original_title": "The Midnight Sky",
            "poster_path": "/51JxCk77ZCqLzbLkrDl9Qho6KUh.jpg",
            "video": false,
            "vote_average": 6.0,
            "overview": "A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.",
            "release_date": "2020-12-10",
            "vote_count": 670,
            "title": "The Midnight Sky",
            "adult": false,
            "backdrop_path": "/dueiWzWc81UAgnbDAyH4Gjqnh4n.jpg",
            "id": 614911,
            "genre_ids": [
                18,
                878
            ],
            "popularity": 2468.413,
            "media_type": "movie"
        },
        {
            "adult": false,
            "backdrop_path": "/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
            "vote_count": 873,
            "title": "The Croods: A New Age",
            "genre_ids": [
                12,
                14,
                10751,
                16
            ],
            "video": false,
            "original_language": "en",
            "original_title": "The Croods: A New Age",
            "poster_path": "/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg",
            "id": 529203,
            "release_date": "2020-11-25",
            "vote_average": 7.8,
            "overview": "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
            "popularity": 2245.647,
            "media_type": "movie"
        },
        {
            "vote_average": 6.0,
            "overview": "When alien invaders capture Earth's superheroes, their kids must learn to work together to save their parents - and the planet.",
            "release_date": "2020-12-25",
            "title": "We Can Be Heroes",
            "adult": false,
            "backdrop_path": "/UgNke0mMQhQdnX2hEu4cN83M0a.jpg",
            "genre_ids": [
                28,
                14,
                10751
            ],
            "vote_count": 135,
            "original_language": "en",
            "original_title": "We Can Be Heroes",
            "poster_path": "/1S21HpcKY6uQ9UAw68aICmrJaq6.jpg",
            "id": 615677,
            "video": false,
            "popularity": 1089.456,
            "media_type": "movie"
        },
        {
            "overview": "A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.",
            "release_date": "2020-09-03",
            "adult": false,
            "backdrop_path": "/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg",
            "id": 553604,
            "genre_ids": [
                28,
                53,
                80,
                18
            ],
            "vote_count": 359,
            "original_language": "en",
            "original_title": "Honest Thief",
            "poster_path": "/zeD4PabP6099gpE0STWJrJrCBCs.jpg",
            "video": false,
            "title": "Honest Thief",
            "vote_average": 6.8,
            "popularity": 2049.644,
            "media_type": "movie"
        },
        {
            "overview": "A WWII pilot traveling with top secret documents on a B-17 Flying Fortress encounters an evil presence on board the flight.",
            "release_date": "2020-12-31",
            "adult": false,
            "backdrop_path": "/aHYUj0hICtWZ5tPiCIm6pWUcjYK.jpg",
            "genre_ids": [
                28,
                18,
                27,
                10752
            ],
            "vote_count": 21,
            "original_language": "en",
            "original_title": "Shadow in the Cloud",
            "poster_path": "/t7EUMSlfUN3jUSZUJOLURAzJzZs.jpg",
            "video": false,
            "id": 675327,
            "vote_average": 6.1,
            "title": "Shadow in the Cloud",
            "popularity": 91.19,
            "media_type": "movie"
        },
        {
            "overview": "John Garrity, his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
            "release_date": "2020-07-29",
            "id": 524047,
            "adult": false,
            "backdrop_path": "/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
            "genre_ids": [
                28,
                53
            ],
            "vote_count": 1181,
            "original_language": "en",
            "original_title": "Greenland",
            "poster_path": "/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg",
            "video": false,
            "title": "Greenland",
            "vote_average": 7.1,
            "popularity": 1548.201,
            "media_type": "movie"
        },
        {
            "genre_ids": [
                14,
                10751,
                12,
                35,
                27
            ],
            "original_language": "en",
            "original_title": "Roald Dahl's The Witches",
            "poster_path": "/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg",
            "video": false,
            "title": "Roald Dahl's The Witches",
            "vote_count": 1046,
            "overview": "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
            "release_date": "2020-10-26",
            "id": 531219,
            "vote_average": 6.8,
            "adult": false,
            "backdrop_path": "/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg",
            "popularity": 589.061,
            "media_type": "movie"
        },
        {
            "overview": "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
            "release_date": "2001-12-18",
            "id": 120,
            "adult": false,
            "backdrop_path": "/vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg",
            "genre_ids": [
                12,
                14,
                28
            ],
            "vote_count": 18308,
            "original_language": "en",
            "original_title": "The Lord of the Rings: The Fellowship of the Ring",
            "poster_path": "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
            "video": false,
            "title": "The Lord of the Rings: The Fellowship of the Ring",
            "vote_average": 8.3,
            "popularity": 109.796,
            "media_type": "movie"
        },
        {
            "adult": false,
            "id": 11,
            "genre_ids": [
                12,
                28,
                878
            ],
            "vote_count": 14829,
            "original_language": "en",
            "original_title": "Star Wars",
            "poster_path": "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
            "title": "Star Wars",
            "video": false,
            "vote_average": 8.2,
            "backdrop_path": "/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg",
            "overview": "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
            "release_date": "1977-05-25",
            "popularity": 166.781,
            "media_type": "movie"
        },
        {
            "adult": false,
            "backdrop_path": "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
            "genre_ids": [
                12,
                878,
                28
            ],
            "id": 299534,
            "original_language": "en",
            "original_title": "Avengers: Endgame",
            "overview": "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
            "poster_path": "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
            "release_date": "2019-04-24",
            "title": "Avengers: Endgame",
            "video": false,
            "vote_average": 8.3,
            "vote_count": 16147,
            "popularity": 224.601,
            "media_type": "movie"
        },
        {
            "vote_average": 7.0,
            "overview": "When a virus threatens to turn the now earth-dwelling friendly alien hybrids against humans, Captain Rose Corley must lead a team of elite mercenaries on a mission to the alien world in order to save what's left of humanity.",
            "release_date": "2020-12-18",
            "adult": false,
            "backdrop_path": "/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg",
            "vote_count": 25,
            "genre_ids": [
                878,
                28
            ],
            "title": "Skylines",
            "original_language": "en",
            "original_title": "Skylines",
            "poster_path": "/2W4ZvACURDyhiNnSIaFPHfNbny3.jpg",
            "id": 560144,
            "video": false,
            "popularity": 62.313,
            "media_type": "movie"
        },
        {
            "vote_average": 6.4,
            "overview": "Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.",
            "release_date": "2020-08-26",
            "adult": false,
            "backdrop_path": "/2AFZyra0Ddwl2oBDhClvD1qSIL6.jpg",
            "vote_count": 1252,
            "genre_ids": [
                28,
                27,
                878
            ],
            "title": "The New Mutants",
            "original_language": "en",
            "original_title": "The New Mutants",
            "poster_path": "/xrI4EnZWftpo1B7tTvlMUXVOikd.jpg",
            "id": 340102,
            "video": false,
            "popularity": 532.454,
            "media_type": "movie"
        },
        {
            "overview": "2020: A year so [insert adjective of choice here], even the creators of Black Mirror couldn't make it up… but that doesn't mean they don't have a little something to add. This comedy event that tells the story of the dreadful year that was — and perhaps still is? The documentary-style special weaves together some of the world's most (fictitious) renowned voices with real-life archival footage.",
            "release_date": "2020-12-27",
            "adult": false,
            "backdrop_path": "/xxEec408VQY7TIvtpxdkUM3Fux6.jpg",
            "genre_ids": [
                35
            ],
            "vote_count": 146,
            "original_language": "en",
            "original_title": "Death to 2020",
            "poster_path": "/w9FPFsPkeiBDn6WwDHFgniWdVJm.jpg",
            "video": false,
            "id": 773655,
            "vote_average": 6.9,
            "title": "Death to 2020",
            "popularity": 447.723,
            "media_type": "movie"
        },
        {
            "genre_ids": [
                28,
                12,
                18,
                14
            ],
            "original_language": "en",
            "original_title": "Mulan",
            "poster_path": "/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg",
            "video": false,
            "vote_average": 7.1,
            "id": 337401,
            "overview": "When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.",
            "release_date": "2020-09-04",
            "vote_count": 3812,
            "title": "Mulan",
            "adult": false,
            "backdrop_path": "/qAKvUu2FSaDlnqznY4VOp5PmjIF.jpg",
            "popularity": 674.265,
            "media_type": "movie"
        },
        {
            "original_language": "en",
            "original_title": "Fatman",
            "poster_path": "/4n8QNNdk4BOX9Dslfbz5Dy6j1HK.jpg",
            "video": false,
            "vote_average": 5.7,
            "overview": "A rowdy, unorthodox Santa Claus is fighting to save his declining business. Meanwhile, Billy, a neglected and precocious 12 year old, hires a hit man to kill Santa after receiving a lump of coal in his stocking.",
            "release_date": "2020-11-13",
            "vote_count": 284,
            "title": "Fatman",
            "adult": false,
            "backdrop_path": "/ckfwfLkl0CkafTasoRw5FILhZAS.jpg",
            "id": 602211,
            "genre_ids": [
                28,
                35,
                14
            ],
            "popularity": 1122.495,
            "media_type": "movie"
        },
        {
            "adult": false,
            "backdrop_path": "/9UFwcWa3lKeAllcW0EvkmOuHqek.jpg",
            "genre_ids": [
                18,
                10402
            ],
            "id": 615667,
            "original_language": "en",
            "original_title": "Ma Rainey's Black Bottom",
            "overview": "Tensions rise when the trailblazing Mother of the Blues and her band gather at a Chicago recording studio in 1927. Adapted from August Wilson's play.",
            "poster_path": "/pvtyxijaBrCSbByXLcUIDDSvc40.jpg",
            "release_date": "2020-11-25",
            "title": "Ma Rainey's Black Bottom",
            "video": false,
            "vote_average": 6.9,
            "vote_count": 183,
            "popularity": 214.575,
            "media_type": "movie"
        },
        {
            "vote_average": 7.9,
            "overview": "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths -- and about the villain who's to blame.",
            "release_date": "2001-11-16",
            "title": "Harry Potter and the Philosopher's Stone",
            "adult": false,
            "backdrop_path": "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
            "genre_ids": [
                12,
                14
            ],
            "vote_count": 19147,
            "original_language": "en",
            "original_title": "Harry Potter and the Philosopher's Stone",
            "poster_path": "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
            "id": 671,
            "video": false,
            "popularity": 198.533,
            "media_type": "movie"
        }
    ],
    "total_pages": 1000,
    "total_results": 20000
}

export default data;